version: '3.9'

services:
  db:
    image: "postgres:15"
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=root 
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# networks:
#   apiman-proxy-external:
#     name: apiman-proxy-external
#     external: true