fix:
	export GO111MODULE="on"

disable:
	export GO111MODULE="off"
run:
	go run main.go

init:
	go mod init github.com/ioannova/alura-golang/gorm

install:
	go get -u gorm.io/gorm
	go get -u gorm.io/driver/sqlite
